const Loan = require("../models/Loan");
const Repayment = require("../models/Repayment");

exports.getAllLoans = async (req, res, next) => {
    try {
        const filter = {};
        if (req.query.status) filter.status = req.query.status.toUpperCase();
        if (req.query.borrower) filter.borrower = req.query.borrower.toLowerCase();

        // Use lean() for fast reads
        const loans = await Loan.find(filter).sort({ createdAt: -1 }).lean();
        res.json({ success: true, data: loans });
    } catch (err) { next(err); }
};

exports.getLoanById = async (req, res, next) => {
    try {
        const loan = await Loan.findOne({ loanId: Number(req.params.id) }).lean();
        if (!loan) return res.status(404).json({ error: "Loan not found" });

        // Fetch EMI schedule automatically generated by Indexer
        const schedule = await Repayment.find({ loanId: loan.loanId })
            .sort({ installmentNumber: 1 })
            .lean();
            
        res.json({ success: true, data: { ...loan, schedule } });
    } catch (err) { next(err); }
};

exports.getStats = async (req, res, next) => {
    try {
        const [total, active, repaid, defaulted, requested] = await Promise.all([
            Loan.countDocuments(),
            Loan.countDocuments({ status: "ACTIVE" }),
            Loan.countDocuments({ status: "REPAID" }),
            Loan.countDocuments({ status: "DEFAULTED" }),
            Loan.countDocuments({ status: "REQUESTED" }),
        ]);

        res.json({ success: true, data: { total, active, repaid, defaulted, requested } });
    } catch (err) { next(err); }
};
